name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs-build]
    
    - name: Create docs structure
      run: |
        mkdir -p docs/notebooks
        mkdir -p docs/_static
        mkdir -p docs/_templates
    
    - name: Convert notebooks to markdown
      run: |
        # Convert demo notebook to markdown
        jupyter nbconvert --to markdown notebooks/Demo.ipynb --output-dir docs/notebooks/
        # Convert India temperature change notebook to markdown  
        jupyter nbconvert --to markdown notebooks/India_temp_change.ipynb --output-dir docs/notebooks/
    
    - name: Generate API documentation
      run: |
        sphinx-apidoc -o docs/api varunayan --force --separate
    
    - name: Build documentation
      run: |
        cd docs
        sphinx-build -b html . _build/html
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
